export const MONSTER_LIST = [
  "Ajarakan",
  "Arkveld",
  "Balahara",
  "Blangonga",
  "Chatacabra",
  "Congalala",
  "Doshaguma",
  "Gore Magala",
  "Gravios",
  "Guardian Arkveld",
  "Guardian Doshaguma",
  "Guardian Ebony Odogaron",
  "Guardian Fulgur Anjanath",
  "Guardian Rathalos",
  "Gypceros",
  "Hirabami",
  "Jin Dahaad",
  "Lala Barina",
  "Mizutsune",
  "Nerscylla",
  "Nu Udra",
  "Quematrice",
  "Rathalos",
  "Rathian",
  "Rey Dau",
  "Rompopolo",
  "Uth Duna",
  "Xu Wu",
  "Yian Kut-Ku",
  "Zoh Shia",

  // Added for Title Update 2
  "Lagiacrus",
  "Seregios",

  // Added fpr Title Update 3
  "Omega Planetes",
] as const;
